# Generated by Django 5.2.16 on 2026-07-24 12:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_cpf_to_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=15),
        ),
    ]
